apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-autonomousdb-workload
spec:
  validationFailureAction: enforce
  rules:
    - name: allow-only-specific-workloads
      match:
        resources:
          kinds:
            - opentofu.upbound.io/v1beta1/Workspace
      validate:
        message: "DB workloads can only be of type OLTP, DW, AJD, or APEX"
        foreach:
          - list: spec.forProvider.env
            pattern:
              name: TF_VAR_db_workload
              value: "?^(OLTP|DW|AJD|APEX)$"
