apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-autonomousdb-workload
spec:
  validationFailureAction: enforce
  rules:
    - name: allow-only-specific-workloads
      match:
        resources:
          kinds:
            - opentofu.upbound.io/v1beta1/Workspace
      validate:
        message: "DB workloads can only be of type OLTP, DW, AJD, or APEX"
        foreach:
          - list: "request.object.spec.forProvider.env"
            deny:
              conditions:
                - key: "{{ element.name }}"
                  operator: Equals
                  value: "TF_VAR_db_workload"
                - key: "{{ element.value }}"
                  operator: NotIn
                  value:
                    - "OLTP"
                    - "DW"
                    - "AJD"
                    - "APEX"

